export const USER_LOGIN = 'USER_LOGIN';
export const TOKEN_ASYNC_STORAGE = 'TOKEN_ASYNC_STORAGE';
export const DATA_ASYNC_STORAGE = 'DATA_ASYNC_STORAGE';
export const GET_PLAYER_STATS = 'GET_PLAYER_STATS';
export const GET_USER_DATA = 'GET_USER_DATA';
